### ISSUE TITLE
How to install HHVM 3.3.1 in Yosemite

### ISSUE THREAD

**Issue by christopherowen** [mcuadros/homebrew-hhvm#122]
# Foreword

This is the first install of HHVM 3.3.1 on OSx 10.10 (Yosemite).  Most of the build system changes required have already been quickly and expertly applied by @denji; this could not be working without @denji.

It uses the GCC 4.9 compiler and toolchain instead of the shipping LLVM compiler and toolchain.  This is a problem for four reasons: 
- It requires the installation of gcc and its toolchain which are very large
- It requires recompiling boost (and two other dependencies) with gcc so that their precompiled, timesaving 'bottles' cannot be used
- It requires recompiling boost (and two other dependencies) with gcc so that other Formulas that link against these libraries will now be broken until they are themselves recompiled with gcc.
- gcc is going to become more and more unstable in OS X from now.

Future effort will be directed at a working HHVM in Yosemite with LLVM/Clang.  Anyone looking to assist should focus their effort here.  Some work is in #137.

While these steps will produce a binary to run, it is not currently able to run php code.  Please help improve the state of things.  Read as: the build system will work but the code will not.

# Preparation

To prove to myself that I finally had a working set of instructions, I deleted all of brew and started from scratch (preserving /Library/Cache/Homebrew so that I didn't have to download all packages again).

1) `rm -rf /usr/local`
2) `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
3) `brew tap mcuadros/homebrew-hhvm`
4) verify that everything is working as expected with: `brew doctor`

# Fix the build

The build instructions in our Formula are not yet perfect, so some additional steps are currently required.  These steps should be made unnecessary in the future.

5a) `brew install binutils`: #133

~~5b) apply patch at the bottom of: #116~~

~~5c) apply patch at the bottom of: #121~~

~~5d) remove patch from hhvm.rb: #134~~

# Prepare special dependencies for linking

HHVM compiled with the gcc toolchain requires that these dependencies are compiled with the gcc toolchain in order to link

6a) `brew install gcc`
6b) `brew install --build-from-source --cc=gcc-4.9 boost gflags glog`

Note, if you didn't start from scratch as I did, you may prefer:
```
brew update
brew upgrade
brew reinstall --build-from-source --cc=gcc-4.9 boost gflags glog
```

# Compile HHVM

7) `brew install hhvm --with-gcc`

# Run hhvm
```sh
$ uname -v
Darwin Kernel Version 14.0.0: Sat Sep 27 03:58:47 PDT 2014; root:xnu-2782.1.97~11/RELEASE_X86_64

$ /usr/local/Cellar/hhvm/3.3.1/bin/hhvm --version
HipHop VM 3.3.1 (rel)
Compiler: heads/master-0-gf389abf84a9be91e94ffe9532646679b6776dd52
Repo schema: e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
Extension API: 20140829
```

**Comment by gverdian** [comment]
I get similar:

$ brew reinstall hhvm --HEAD --with-gcc --verbose 
==> Reinstalling hhvm with --with-gcc
==> Cloning https://github.com/facebook/hhvm.git
git clone --depth 1 --branch master https://github.com/facebook/hhvm.git /Library/Caches/Homebrew/hhvm--git
Cloning into '/Library/Caches/Homebrew/hhvm--git'...
remote: Counting objects: 42818, done.
remote: Compressing objects: 100% (32805/32805), done.
remote: Total 42818 (delta 6615), reused 30854 (delta 5600)
Receiving objects: 100% (42818/42818), 21.35 MiB | 699.00 KiB/s, done.
Resolving deltas: 100% (6615/6615), done.
Checking connectivity... done.
Checking out files: 100% (55750/55750), done.
git config homebrew.cacheversion 0
git submodule sync --recursive
git submodule update --init --recursive
Submodule 'third-party' (https://github.com/hhvm/hhvm-third-party.git) registered for path 'third-party'
Cloning into 'third-party'...
remote: Counting objects: 2475, done.
remote: Total 2475 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2475/2475), 6.88 MiB | 356.00 KiB/s, done.
Resolving deltas: 100% (1272/1272), done.
Checking connectivity... done.
Submodule path 'third-party': checked out 'd0cad57b5427f84af8f77d60b8b53de4aaea4694'
Submodule 'folly' (https://github.com/facebook/folly.git) registered for path 'folly/src'
Submodule 'proxygen/src' (https://github.com/facebook/proxygen) registered for path 'proxygen/src'
Submodule 'thrift/src' (https://github.com/facebook/fbthrift.git) registered for path 'thrift/src'
Cloning into 'folly/src'...
remote: Counting objects: 10387, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 10387 (delta 33), reused 0 (delta 0)
Receiving objects: 100% (10387/10387), 4.62 MiB | 707.00 KiB/s, done.
Resolving deltas: 100% (7951/7951), done.
Checking connectivity... done.
Submodule path 'third-party/folly/src': checked out '6f9b619d9ffc219296a818a83266d60628e6aedd'
Cloning into 'proxygen/src'...
remote: Counting objects: 2280, done.
remote: Total 2280 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2280/2280), 866.05 KiB | 96.00 KiB/s, done.
Resolving deltas: 100% (1695/1695), done.
Checking connectivity... done.
Submodule path 'third-party/proxygen/src': checked out '8a602aa40383d6dddbdcb2a951067b9923edfc74'
Cloning into 'thrift/src'...
remote: Counting objects: 11272, done.
remote: Compressing objects: 100% (570/570), done.
remote: Total 11272 (delta 332), reused 0 (delta 0)
Receiving objects: 100% (11272/11272), 6.24 MiB | 894.00 KiB/s, done.
Resolving deltas: 100% (8288/8288), done.
Checking connectivity... done.
Submodule path 'third-party/thrift/src': checked out 'bba5d4590ff71e8f34ce4f90a8d7b2cf867ca3d0'
==> Checking out branch master
git checkout-index -a -f --prefix=/private/tmp/hhvm-GlgybS/
git submodule foreach --recursive git checkout-index -a -f --prefix=/private/tmp/hhvm-GlgybS/${toplevel/\/Library\/Caches\/Homebrew\/hhvm--git/}/$path/
Entering 'third-party'
Entering 'third-party/folly/src'
Entering 'third-party/proxygen/src'
Entering 'third-party/thrift/src'
==> Downloading https://github.com/facebook/hhvm/pull/3517.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-ba8c3dbf1e75957b6733aaf52207d4e55f1d286a.diff
==> Verifying hhvm--patch-ba8c3dbf1e75957b6733aaf52207d4e55f1d286a.diff checksum
==> Patching
/usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-50unSg/3517.diff
patching file CMake/HPHPSetup.cmake
patching file hphp/runtime/base/emulate-zend.cpp
Hunk #1 succeeded at 229 (offset -6 lines).
patching file hphp/runtime/base/program-functions.cpp
Hunk #1 FAILED at 1191.
1 out of 1 hunk FAILED -- saving rejects to file hphp/runtime/base/program-functions.cpp.rej
patching file hphp/util/compilation-flags.h
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-50unSg/3517.diff

uname -a
Darwin x4.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

**Comment by ivarflakstad** [comment]
Almost exactly same error on my machine, only the patch is different.

Hunk #1 FAILED at 1191.
1 out of 1 hunk FAILED -- saving rejects to file hphp/runtime/base/program-functions.cpp.rej
patching file hphp/util/compilation-flags.h
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-ePwpvX/3517.diff

I have exactly the same uname output.

**Comment by csandanov** [comment]
I have the same issue with similar output
