### ISSUE TITLE
While i download, i get an error like this:

### ISSUE THREAD

**Issue by mehmetdavut** [mcuadros/homebrew-hhvm#138]
==> Installing hhvm from mcuadros/homebrew-hhvm
==> Cloning https://github.com/facebook/hhvm.git
Updating /Library/Caches/Homebrew/hhvm--git
==> Downloading https://github.com/facebook/hhvm/pull/3517.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-ba8c3dbf1e75957b6733aaf52207d4e55f1d286a.diff
==> Patching
patching file CMake/HPHPSetup.cmake
patching file hphp/runtime/base/emulate-zend.cpp
Hunk #1 succeeded at 229 (offset -6 lines).
patching file hphp/runtime/base/program-functions.cpp
Hunk #1 succeeded at 1217 (offset 26 lines).
patching file hphp/util/compilation-flags.h
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIENT_INCLUDE_PATH=/usr/loc
==> make -j4
1 error generated.
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/experimental/wangle/concurrent/ThreadPoolExecutor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/mcuadros/homebrew-hhvm/issues

**Comment by reanimus** [comment]
Any progress/workaround for this? I'm still getting errors with the current build. :(

**Comment by reanimus** [comment]
Still getting this.

```
==> Installing hhvm
==> Downloading https://github.com/facebook/hhvm/archive/HHVM-3.4.2.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/facebook/hhvm/commit/df1ac0a7371c818d3d4b5c85859905e373145446.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-d2f5235da22e5c80c9570dfb7fe2db94bb5d11d5.diff
==> Downloading https://github.com/facebook/hhvm/commit/d65448c.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-d735bb7012c748fed65fdebfe9d2e9ee9bf19649.diff
==> Downloading https://github.com/facebook/hhvm/pull/3517.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-ba8c3dbf1e75957b6733aaf52207d4e55f1d286a.diff
==> Patching
patching file CMake/HPHPFindLibs.cmake
patching file hphp/runtime/ext/openssl/ext_openssl.cpp
patching file CMake/HPHPSetup.cmake
patching file CMake/HPHPSetup.cmake
patching file hphp/runtime/base/emulate-zend.cpp
Hunk #1 succeeded at 229 (offset -6 lines).
patching file hphp/runtime/base/program-functions.cpp
Hunk #1 succeeded at 1217 (offset 26 lines).
patching file hphp/util/compilation-flags.h
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
==> Checking out revision 38af35db27a4d962adaefde343dc6dcfc495c8b5
==> Cloning https://github.com/facebook/folly.git
Updating /Library/Caches/Homebrew/hhvm--folly--git
==> Checking out revision acc54589227951293f8d3943911f4311468605c9
==> Cloning https://github.com/facebook/fbthrift.git
Updating /Library/Caches/Homebrew/hhvm--thrift--git
==> Checking out revision 378e954ac82a00ba056e6fccd5e1fa3e76803cc8
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIENT_INCLUDE_PATH=/usr/local/opt/imap-uw/include/imap -DCMAKE_INCLUDE_PATH="/usr/local/include:/usr/include" -DCMAKE_INSTALL_P
==> make -j8
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/experimental/wangle/concurrent/ThreadPoolExecutor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
[ 21%] Built target hack
make: *** [all] Error 2
```
