### ISSUE TITLE
Failed to download resource "binutilsfb"

### ISSUE THREAD

**Issue by vhanla** [mcuadros/homebrew-hhvm#146]
After _brew install hhvm --HEAD_ it stops because it can't find binutils-**2.24**
It seems that _binutils-2.24.tar.gz_ is not available anymore 

But _brew install binutils_ installs version **2.25** 
_brew install binutilsfb_ tries to install _binutils-2.24_ 

Is it different to install _binutils_ than _binutilsfb_?

**Comment by vhanla** [comment]
Tried again and it downloads now. It might have been something related to the downloads server.

**Comment by denji** [comment]
@vhanla Check this https://github.com/mcuadros/homebrew-hhvm/issues/111#issuecomment-60781545
> Is it different to install binutils than binutilsfb?
