### ISSUE TITLE
Prioritize MacOS build/binary support

### ISSUE THREAD

**Issue by denji** [mcuadros/homebrew-hhvm#147]
Before creating new issues, check here https://github.com/facebook/hhvm/issues/4444

**Comment by my2ter** [comment]
Hey @denji,

What's the current situation with this? As far as I know - from all the related problems listed with 10.10.x -it is still impossible to build hhvm with homebrew. 

Also the README states that it supports up to 10.11 but no reference is made to this bug. It is a bit confusing...

Thanks.

**Comment by mnapoli** [comment]
High, I'd also like to know the current situation? The readme doesn't mention any issue: https://github.com/mcuadros/homebrew-hhvm#usage Is it supposed to work?
