### ISSUE TITLE
Can't install: "Error: Failed to download resource \"hhvm--third-party\""

### ISSUE THREAD

**Issue by bgwines-shmoop** [mcuadros/homebrew-hhvm#148]
Hi, there,

I'm experiencing the following issue when installing homebrew-hhvm. I've run `brew update`. Am I perhaps doing something wrong?

Thanks for your attention!

~/ > brew install hhvm
==> Installing hhvm from mcuadros/homebrew-hhvm
==> Downloading https://github.com/facebook/hhvm/archive/HHVM-3.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/hhvm-3.4.2.tar.gz
==> Downloading https://github.com/facebook/hhvm/commit/df1ac0a7371c818d3d4b5c85859905e3
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-d2f5235da22e5c80c9570dfb7fe2db94bb5d11d5.diff
==> Downloading https://github.com/facebook/hhvm/commit/d65448c.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-d735bb7012c748fed65fdebfe9d2e9ee9bf19649.diff
==> Downloading https://github.com/facebook/hhvm/pull/3517.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-ba8c3dbf1e75957b6733aaf52207d4e55f1d286a.diff
==> Patching
patching file CMake/HPHPFindLibs.cmake
patching file hphp/runtime/ext/openssl/ext_openssl.cpp
patching file CMake/HPHPSetup.cmake
patching file CMake/HPHPSetup.cmake
patching file hphp/runtime/base/emulate-zend.cpp
Hunk #1 succeeded at 229 (offset -6 lines).
patching file hphp/runtime/base/program-functions.cpp
Hunk #1 succeeded at 1217 (offset 26 lines).
patching file hphp/util/compilation-flags.h
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
fatal: reference is not a tree: 38af35db27a4d962adaefde343dc6dcfc495c8b5
Error: Failed to download resource "hhvm--third-party"
Failure while executing: git checkout -q -f 38af35db27a4d962adaefde343dc6dcfc495c8b5 --
~/ >

**Comment by denji** [comment]
Perhaps we should pre-clear the cache?
`rm -rf /Library/Caches/Homebrew/hhvm--third-party--git`
or complete clearing the cache Homebrew
`rm -rf /Library/Caches/Homebrew`

**Comment by bgwines-shmoop** [comment]
Dang; that was a fast response. Thanks!

That worked -- I'll keep that in mind for the future whenever I run into similar issues.
