### ISSUE TITLE
osx 10.10.1 [ 22%] Built target sqlite3

### ISSUE THREAD

**Issue by lamjack** [mcuadros/homebrew-hhvm#149]
brew install hhvm --with-gcc --verbose

[ 22%] Built target sqlite3
make: *** [all] Error 2
/usr/libexec/java_home --failfast 
==> Formula
Tap: mcuadros/homebrew-hhvm
Path: /usr/local/Library/Taps/mcuadros/homebrew-hhvm/Formula/hhvm.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 4a465a14b9e9cd787ecbc6d9c07f9128e477fa40
Last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.1-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.0/bin/ruby
/usr/libexec/java_home --failfast 
Java: 1.6.0_65
==> ENV
CC: /usr/local/opt/gcc/bin/gcc-4.9
CXX: /usr/local/opt/gcc/bin/g++-4.9
LD: /usr/local/opt/gcc/bin/gcc-4.9
OBJC: clang
OBJCXX: clang++
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/binutilsfb:/usr/local/opt/curl:/usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/jemallocfb:/usr/local/opt/libarchive:/usr/local/opt/libxml2:/usr/local/opt/libxslt:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/cloog/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/gflags/lib/pkgconfig:/usr/local/opt/glog/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/imagemagick/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/libelf/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/libmemcached/lib/pkgconfig:/usr/local/opt/libssh2/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libxslt/lib/pkgconfig:/usr/local/opt/libzip/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/oniguruma/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/opt/libxslt/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/cloog/bin:/usr/local/opt/gcc/bin:/usr/local/opt/openssl/bin:/usr/local/opt/binutilsfb/bin:/usr/local/opt/curl/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/gd/bin:/usr/local/opt/gettext/bin:/usr/local/opt/gflags/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/xz/bin:/usr/local/opt/imagemagick/bin:/usr/local/opt/imap-uw/bin:/usr/local/opt/jemallocfb/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/libevent/bin:/usr/local/opt/memcached/bin:/usr/local/opt/libmemcached/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libzip/bin:/usr/local/opt/lz4/bin:/usr/local/opt/mcrypt/bin:/usr/local/opt/objective-caml/bin:/usr/local/opt/oniguruma/bin:/usr/local/opt/pcre/bin:/usr/local/opt/re2c/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/mysql/bin:/usr/local/opt/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Error: hhvm 3.4.2 did not build
Logs:
     /Users/jack/Library/Logs/Homebrew/hhvm/01.cmake
     /Users/jack/Library/Logs/Homebrew/hhvm/01.cmake.cc
     /Users/jack/Library/Logs/Homebrew/hhvm/02.make
     /Users/jack/Library/Logs/Homebrew/hhvm/02.make.cc

**Comment by rhukster** [comment]
I have the same issue on 10.10.2

```
brew install hhvm --with-gcc --with-mariadb --verbose

[ 22%] Built target sqlite3
make: *** [all] Error 2
==> Formula
Tap: mcuadros/homebrew-hhvm
Path: /usr/local/Library/Taps/mcuadros/homebrew-hhvm/Formula/hhvm.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 66b1bb0445b66a07e0e5d7a07fd6cfcb930379b0
Last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit penryn
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_65
==> ENV
CC: /usr/local/opt/gcc/bin/gcc-4.9
CXX: /usr/local/opt/gcc/bin/g++-4.9
LD: /usr/local/opt/gcc/bin/gcc-4.9
OBJC: clang
OBJCXX: clang++
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/binutilsfb:/usr/local/opt/curl:/usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/jemallocfb:/usr/local/opt/libarchive:/usr/local/opt/libxml2:/usr/local/opt/libxslt:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/cloog/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/gflags/lib/pkgconfig:/usr/local/opt/glog/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/imagemagick/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/libelf/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/libmemcached/lib/pkgconfig:/usr/local/opt/libssh2/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libxslt/lib/pkgconfig:/usr/local/opt/libzip/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/oniguruma/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/opt/libxslt/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/cloog/bin:/usr/local/opt/gcc/bin:/usr/local/opt/openssl/bin:/usr/local/opt/binutilsfb/bin:/usr/local/opt/curl/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/gd/bin:/usr/local/opt/gettext/bin:/usr/local/opt/gflags/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/xz/bin:/usr/local/opt/imagemagick/bin:/usr/local/opt/imap-uw/bin:/usr/local/opt/jemallocfb/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/libevent/bin:/usr/local/opt/memcached/bin:/usr/local/opt/libmemcached/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libzip/bin:/usr/local/opt/lz4/bin:/usr/local/opt/mcrypt/bin:/usr/local/opt/objective-caml/bin:/usr/local/opt/oniguruma/bin:/usr/local/opt/pcre/bin:/usr/local/opt/re2c/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/mariadb/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: hhvm 3.4.2 did not build
Logs:
     /Users/rhuk/Library/Logs/Homebrew/hhvm/01.cmake
     /Users/rhuk/Library/Logs/Homebrew/hhvm/01.cmake.cc
     /Users/rhuk/Library/Logs/Homebrew/hhvm/02.make
```

**Comment by lovek323** [comment]
I am also having this issue

**Comment by dmayle** [comment]
This appears to be a clang vs gcc issue on Mac.  The logs contain a reference to features.h, which is linux and gcc only.  This has been fixed upstream, but the formula is pegged to older versions of thrift and folly which exhibit the problem.

**Comment by denji** [comment]
> [ 22%] Built target sqlite3
make: *** [all] Error 2
/usr/libexec/java_home --failfast 

Can try to refresh the module sqlite3 `brew upgrade` (he checks java)
```
~ /usr/libexec/java_home --failfast
/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

This does not apply to hhvm directly, I close my
