### ISSUE TITLE
Folly: couldn't understand kern.osversion `14.1.0'

### ISSUE THREAD

**Issue by dwsturgeon** [mcuadros/homebrew-hhvm#154]
is anyone getting this error:

1 error generated.
make[2]: *** [third-party/folly/CMakeFiles/folly.dir/folly/experimental/wangle/concurrent/ThreadPoolExecutor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [third-party/folly/CMakeFiles/folly.dir/all] Error 2
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'

**Comment by denji** [comment]
@dwsturgeon I updated folly to version 26 facebook/folly@7d2497f

**Comment by dwsturgeon** [comment]
Thank you denji, your always the first to help with issues!
