### ISSUE TITLE
couldn't understand kern.osversion `14.1.0'

### ISSUE THREAD

**Issue by KeinborgMichael** [mcuadros/homebrew-hhvm#155]
==> Cloning https://github.com/facebook/fbthrift.git
Updating /Library/Caches/Homebrew/hhvm--thrift--git
==> Checking out revision d30280a33ed2c67672b0295872397e5affb60f8c
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/
==> make -j8
cp hh_client.opt ../bin/hh_client
cp hh_single.opt ../bin/hh_single_type_check
/usr/local/Cellar/cmake/3.1.3/bin/cmake -E cmake_progress_report /usr/local/Cellar/hhvm/3.4.2/src/CMakeFiles 
[ 21%] Built target hack
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'

**Comment by originalpete** [comment]
This happens to me too. I get the above error when I run:

```
brew install hhvm 
```

And I get the other error ("Hunk #1 FAILED at 1191.") when I run 
```
brew install hhvm --HEAD
```

Is there *any* way to install HHVM on Yosemite at the moment?

**Comment by christopherowen** [comment]
@originalpete a virtual machine
