### ISSUE TITLE
error: 'elf.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by Daniel15** [mcuadros/homebrew-hhvm#156]
Build is failing for me on OS X 10.10.2 with these errors:
```
/usr/local/Cellar/hhvm/3.4.2/src/third-party/folly/folly/experimental/symbolizer/Elf.h:23:10: error: 'elf.h' file not found with <angled> include; use "quotes" instead
#include <elf.h>
         ^~~~~~~
         "elf.h"
/usr/local/Cellar/hhvm/3.4.2/src/third-party/folly/folly/experimental/symbolizer/Elf.h:24:10: fatal error: 'link.h' file not found
#include <link.h>  // For ElfW()
         ^
```

`brew gist-logs hhvm` output: https://gist.github.com/anonymous/a690a0834e3e22bf5f47

**Comment by denji** [comment]
@Daniel15  I have doubts that fb though sometimes verifies working that the Illumos/BSD/Darwin-OSX.

Let's hope that soon will work on LLVM/Clang at the moment it works through custom GCC-toolchan You can find information here [Known Problems](https://github.com/mcuadros/homebrew-hhvm).

The latest proven branch 3.4.x (3.5/3.6 no longer work with the new dependencies [proxygen](https://github.com/facebook/proxygen)).
