### ISSUE TITLE
hhvm failed to build on 10.10.2

### ISSUE THREAD

**Issue by schokocappucino** [mcuadros/homebrew-hhvm#157]
I can't compile hhvm
My osx version is 10.10.2, xcode is up to date and I tried installing using `$ brew install hhvm --with-mariadb`.

```
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/
==> make -j4
cp hh_client.opt ../bin/hh_client
cp hh_single.opt ../bin/hh_single_type_check
/usr/local/Cellar/cmake/3.2.1/bin/cmake -E cmake_progress_report /usr/local/Cellar/hhvm/3.4.2/src/CMakeFiles 
[ 18%] Built target hack
make: *** [all] Error 2
```

Gist log: https://gist.github.com/anonymous/7a1a79a8644e3a124800

**Comment by paales** [comment]
Got the same error, have tried to install hhvm on osx multiple times in the last year, but never got it working :(

**Comment by mikebc23** [comment]
Got the same error with 10.10.3

Updating /Library/Caches/Homebrew/hhvm--thrift--git
==> Checking out revision b9389429aa71b6b4d2876134c8f50143a044d653
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIENT_INCLUDE_PATH=/usr/local/opt/imap-uw/include/imap -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_INCLUDE_PATH="/usr/local/include:/usr/include" -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/hhvm/3.4.2 -DCMAKE_LIBRARY_PATH
==> make -j8
cp hh_client.opt ../bin/hh_client
cp hh_single.opt ../bin/hh_single_type_check
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /usr/local/Cellar/hhvm/3.4.2/src/CMakeFiles 
[ 19%] Built target hack

**Comment by denji** [comment]
@mikebc23 `3.4.2` support only GCC, You need to use the most recent version.
- [Known Problems](https://github.com/mcuadros/homebrew-hhvm#known-problems)
- mcuadros/homebrew-hhvm#147
