### ISSUE TITLE
error in 10.10 install

### ISSUE THREAD

**Issue by michaeljs1990** [mcuadros/homebrew-hhvm#164]
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
fatal: reference is not a tree: 38af35db27a4d962adaefde343dc6dcfc495c8b5
Error: Failed to download resource "hhvm--third-party"
Failure while executing: git checkout -q -f 38af35db27a4d962adaefde343dc6dcfc495c8b5 --

**Comment by denji** [comment]
Maintainer `hhvm/hhvm-third-party` rebase source tree `/Library/Caches/Homebrew/hhvm--third-party--git`?

You can clear the cache homebrew re-fetching building:
```
brew prune
brew cleanup -s --force
rm -rf /Library/Caches/Homebrew
```

**Comment by michaeljs1990** [comment]
Didn't notice it was pulling from Caches sorry about that! thanks @denji.

**Comment by michaeljs1990** [comment]
==> Installing mcuadros/hhvm/hhvm
==> Downloading https://github.com/facebook/hhvm/archive/HHVM-3.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/hhvm-3.4.2.tar.gz
==> Downloading https://rawgit.com/mcuadros/homebrew-hhvm/master/patches/3.4.x/check_rand-egd.patch
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-b309d4117f3ba4aba01df96d95fe02fa627ba0d88e97d40af27618fe4ea32d56.patch
==> Downloading https://rawgit.com/mcuadros/homebrew-hhvm/master/patches/3.4.x/segaddr-32bit.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-4cb98ff600860a67dc0352ffb8515c8451f233211c4294e08d7cd7d647a5bb52.diff
==> Downloading https://rawgit.com/mcuadros/homebrew-hhvm/master/patches/3.4.x/userland_path.diff
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-a7ebe733f584027a5131a04b0dc037c259743a1f07931530475951ff9e697853.diff
==> Patching
patching file CMake/HPHPFindLibs.cmake
patching file hphp/runtime/ext/openssl/ext_openssl.cpp
patching file CMake/HPHPSetup.cmake
patching file hphp/runtime/base/emulate-zend.cpp
patching file hphp/runtime/base/program-functions.cpp
==> Cloning https://github.com/hhvm/hhvm-third-party.git
Updating /Library/Caches/Homebrew/hhvm--third-party--git
warning: unable to rmdir mcrouter/src: Directory not empty
warning: unable to rmdir proxygen/src: Directory not empty
warning: unable to rmdir re2/src: Directory not empty
warning: unable to rmdir squangle/src: Directory not empty
warning: unable to rmdir webscalesqlclient/webscalesql-5.6: Directory not empty
==> Checking out revision 38af35db27a4d962adaefde343dc6dcfc495c8b5
==> Cloning https://github.com/facebook/folly.git
Updating /Library/Caches/Homebrew/hhvm--folly--git
==> Checking out revision 88fb213fe19af92f50ee851a477c73a103dbcfe1
==> Cloning https://github.com/facebook/fbthrift.git
Updating /Library/Caches/Homebrew/hhvm--thrift--git
==> Checking out revision b9389429aa71b6b4d2876134c8f50143a044d653
==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIENT_INCLUDE_PATH=/usr/local/opt/imap-uw/include/imap -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_INCLUDE_PATH="/usr/local/include:/usr/
==> make -j8
cp hh_client.opt ../bin/hh_client
cp hh_single.opt ../bin/hh_single_type_check
/usr/local/Cellar/cmake/3.2.2/bin/cmake -E cmake_progress_report /usr/local/Cellar/hhvm/3.4.2/src/CMakeFiles 
[ 20%] Built target hack
make: *** [all] Error 2

is the next one that comes up... I really have no idea what to make of this one though.

**Comment by denji** [comment]
--HEAD --verbose

**Comment by michaeljs1990** [comment]
running now... that was the single fastest response I have ever seen btw haha.

**Comment by michaeljs1990** [comment]
```
Tap: mcuadros/homebrew-hhvm
Path: /usr/local/Library/Taps/mcuadros/homebrew-hhvm/Formula/hhvm.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 63e769c0a88af73d9b2892bd9f83060090a43ff7
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3.1
CLT: 6.3.1.0.1.1429149539
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.7.0_71
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/binutilsfb:/usr/local/opt/curl:/usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/jemallocfb:/usr/local/opt/libarchive:/usr/local/opt/libxml2:/usr/local/opt/libxslt:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/gd/lib/pkgconfig:/usr/local/opt/glog/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/imagemagick/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/libelf/lib/pkgconfig:/usr/local/opt/libevent/lib/pkgconfig:/usr/local/opt/libmemcached/lib/pkgconfig:/usr/local/opt/libssh2/lib/pkgconfig:/usr/local/opt/libvpx/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libxslt/lib/pkgconfig:/usr/local/opt/libzip/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/oniguruma/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/curl/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/opt/libxml2/share/aclocal:/usr/local/opt/libxslt/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/openssl/bin:/usr/local/opt/binutilsfb/bin:/usr/local/opt/curl/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/fontconfig/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/libtiff/bin:/usr/local/opt/gd/bin:/usr/local/opt/gettext/bin:/usr/local/opt/gflags/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/xz/bin:/usr/local/opt/imagemagick/bin:/usr/local/opt/imap-uw/bin:/usr/local/opt/jemallocfb/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/libevent/bin:/usr/local/opt/memcached/bin:/usr/local/opt/libmemcached/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libzip/bin:/usr/local/opt/lz4/bin:/usr/local/opt/mcrypt/bin:/usr/local/opt/objective-caml/bin:/usr/local/opt/oniguruma/bin:/usr/local/opt/pcre/bin:/usr/local/opt/re2c/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Error: mcuadros/hhvm/hhvm HEAD did not build
Logs:
     /Users/mschuett/Library/Logs/Homebrew/hhvm/01.cmake
     /Users/mschuett/Library/Logs/Homebrew/hhvm/01.cmake.cc
     /Users/mschuett/Library/Logs/Homebrew/hhvm/02.make
     /Users/mschuett/Library/Logs/Homebrew/hhvm/02.make.cc
```

**Comment by michaeljs1990** [comment]
I'm trying --with-gcc now.

**Comment by denji** [comment]
- https://github.com/mcuadros/homebrew-hhvm#known-problems
- mcuadros/homebrew-hhvm#160
