### ISSUE TITLE
What happened to the repo?

### ISSUE THREAD

**Issue by bolvarak** [mcuadros/homebrew-hhvm#166]
The repo folders seemed to have disappeared.  The "patches" folder is no longer there...

**Comment by denji** [comment]
I spend a final test, HHVM-3.7 we need only [one patch](https://github.com/mcuadros/homebrew-hhvm/blob/ba8589550116c889bbe78413f17402c2c09f6d14/Formula/hhvm.rb#L301-L332) it changes the way the default location of configuration files `{hhvm.php}.ini`. Another defect, if we use the implementation of llvm-3.6.1 of homebrew we have no issues `std::`, `thread-local (thread local storage)`.
But if we use `Apple LLVM version 7.0.0 (clang-700.0.53)` from XCode 7 it may [not work correctly with some overrides](https://github.com/mcuadros/homebrew-hhvm/blob/5c87c792a3d440e2cb94c2846b10a7fb455c8ea8/Formula/hhvm.rb#L276-L281)

**Comment by GerDner** [comment]
Error: Failed to download resource "hhvm--patch"
Download failed: https://raw.githubusercontent.com/mcuadros/homebrew-hhvm/master/patches/3.4.x/check_rand-egd.patch
