### ISSUE TITLE
undefined method `desc' for Formulary::Formulae::Hhvm:Class

### ISSUE THREAD

**Issue by datomnurdin** [mcuadros/homebrew-hhvm#168]
I got this error message then trying to install HHVM via Brew.

```
undefined method `desc' for Formulary::Formulae::Hhvm:Class
```

![screen shot 2015-07-06 at 1 50 33 pm](https://cloud.githubusercontent.com/assets/5416242/8516381/093e9000-23e6-11e5-87b2-757192020b45.png)

Please advice. Thank you.

**Comment by denji** [comment]
You must upgrade your kernel homebrew before using hhvm:
`brew update`

In the latest version of the homebrew has the support of the directive `desc` to indicate descriptions.
