### ISSUE TITLE
Another attempt with --HEAD --verbose

### ISSUE THREAD

**Issue by peco8** [mcuadros/homebrew-hhvm#173]
I tried it with "--HEAD --verbose", output this error below

![screen shot 2015-08-10 at 10 16 24](https://cloud.githubusercontent.com/assets/4458427/9174218/7848e04c-3fb9-11e5-9d13-6b5e603d04d9.png)
![screen shot 2015-08-10 at 10 16 47](https://cloud.githubusercontent.com/assets/4458427/9174220/7993dba0-3fb9-11e5-9f61-87d2d37efe71.png)

**Comment by denji** [comment]
Duplicated, but more detailed: https://github.com/mcuadros/homebrew-hhvm/issues/172#issuecomment-131800605
