### ISSUE TITLE
HHVM Official tap announcement

### ISSUE THREAD

**Issue by Maks3w** [mcuadros/homebrew-hhvm#176]
HHVM has announce an initial port to Mac

http://hhvm.com/blog/10043/experimental-mac-os-x-support

**Comment by mcuadros** [comment]
great news! I think that we should close this adding a not pointing to the new one.  

/cc @denji

**Comment by denji** [comment]
Add link to the official brew-tap https://github.com/hhvm/homebrew-hhvm and leave this as an inactive archive. I think now we can keep this repository is inactive?

**Comment by mcuadros** [comment]
Here it is: https://github.com/mcuadros/homebrew-hhvm 

A big thanks to @denji to keep this project alive during the last months.
