### ISSUE TITLE
hhvm does not compile on Mac Os

### ISSUE THREAD

**Issue by akaias** [mcuadros/homebrew-hhvm#177]
hi there,

when i try to install hhvm on my mac it fails with

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libwangle.a(Dummy.cpp.o) has no symbols

i have 
`xcodebuild -version`

> Xcode 7.1
> Build version 7B91b

`brew install hhvm`

> ==> Installing hhvm from mcuadros/homebrew-hhvm
> ==> Downloading https://github.com/facebook/hhvm/archive/HHVM-3.9.1.tar.gz
> Already downloaded: /Library/Caches/Homebrew/hhvm-3.9.1.tar.gz
> ==> Downloading https://github.com/facebook/hhvm/commit/ed1ec181734a2826d2fd1e49d12b1d51f2785061.patch
> Already downloaded: /Library/Caches/Homebrew/hhvm--patch-3b8b4c75181fa7c3154e41530040d061b2f1a6c1357101a43eb65bf307875cf3.patch
> ==> Patching
> patching file CMake/HPHPSetup.cmake
> patching file CMake/Options.cmake
> Hunk #1 succeeded at 29 (offset -2 lines).
> patching file hphp/runtime/base/emulate-zend.cpp
> patching file hphp/runtime/base/program-functions.cpp
> Hunk #1 succeeded at 1365 (offset -5 lines).
> ==> Cloning https://github.com/hhvm/hhvm-third-party.git
> Updating /Library/Caches/Homebrew/hhvm--third-party--git
> ==> Checking out revision 5cfbd0ea334de25115546a08a9dbd2954c6f5ed5
> ==> cmake . -DBOOST_INCLUDEDIR=/usr/local/opt/boost/include -DBOOST_LIBRARYDIR=/usr/local/opt/boost/lib -DCCLIENT_INCLUDE_PATH=/usr/local/opt/imap-uw/include/imap -DCMAKE_C_FLAGS=-
> ==> make install
> Last 15 lines from /Users/akaias/Library/Logs/Homebrew/hhvm/02.make:
> cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/squangle && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/squangle.dir/link.txt --verbose=1
> /usr/bin/ar cq libsquangle.a  CMakeFiles/squangle.dir/squangle/logger/DBEventCounter.cpp.o CMakeFiles/squangle.dir/squangle/logger/DBEventLogger.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/AsyncConnectionPool.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/AsyncHelpers.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/AsyncMysqlClient.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/Connection.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/DbResult.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/FutureAdapter.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/Operation.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/OperationBatch.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/Query.cpp.o CMakeFiles/squangle.dir/squangle/mysql_client/Row.cpp.o
> /usr/bin/ranlib libsquangle.a
> [ 28%] Built target squangle
> [ 28%] Building CXX object third-party/wangle/CMakeFiles/wangle.dir/src/wangle/ssl/TLSTicketKeyManager.cpp.o
> cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle && /usr/local/opt/llvm/bin/clang++   -DDEFAULT_CONFIG_DIR=\"/usr/local/etc\" -DENABLE_FASTCGI=1 -DFOLLY_HAVE_MALLOC_H=0 -DFOLLY_HAVE_PTHREAD_ATFORK=1 -DFOLLY_HAVE_SCHED_H=1 -DFOLLY_HAVE_WEAK_SYMBOLS=1 -DFOLLY_NO_CONFIG=1 -DFOLLY_USE_LIBCPP=1 -DHAVE_BOOST1_49 -DHAVE_CURL_MULTI_WAIT -DHAVE_LIBDL -DHHVM -DHHVM_DYNAMIC_EXTENSION_DIR=\"/usr/local/Cellar/hhvm/3.9.1/lib/hhvm/extensions\" -DHPHP_OSS=1 -DLIBDWARF_CONST_NAME -DMACOSX_DEPLOYMENT_TARGET=10.6 -DMAC_OS_X_VERSION_MIN_REQUIRED=MAC_OS_X_VERSION_10_6 -DNDEBUG -DNO_HARDWARE_COUNTERS=1 -DNO_LIB_GFLAGS -DNO_TCMALLOC=1 -DOPENSSL_NO_RAND_EGD -DPACKAGE=hhvm -DPACKAGE_VERSION=Release -DPHP_MYSQL_UNIX_SOCK_ADDR=\"/tmp/mysql.sock\" -DRELEASE=1 -DSKIP_USER_CHANGE=1 -DTHRIFT_MUTEX_EMULATE_PTHREAD_TIMEDLOCK -DUSE_EDITLINE -DUSE_JEMALLOC=1 -D_GNU_SOURCE -D_PTHREADS=1 -D_REENTRANT=1 -D__STDC_FORMAT_MACROS -I/usr/local/opt/readline/include -L/usr/local/opt/readline/lib -Wall -std=gnu++11 -stdlib=libc++ -fno-omit-frame-pointer -Woverloaded-virtual -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings -Wno-invalid-offsetof -fno-operator-names -Wno-error=array-bounds -Wno-error=switch -Werror=format-security -Wno-unused-result -Wno-sign-compare -Wno-attributes -Wno-maybe-uninitialized -Wno-mismatched-tags -Wno-unknown-warning-option -Wno-return-type-c-linkage -Qunused-arguments -march=native -O3 -DNDEBUG -I/usr/local/include -I/usr/local/opt/glog/include -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/re2/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/squangle/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/webscalesqlclient/src/include -I/usr/local/opt/pcre/include -I/usr/local/opt/libevent/include -I/usr/local/opt/curl/include -I/usr/local/opt/libxml2/include/libxml2 -I/usr/local/opt/lz4/include -I/usr/local/opt/libzip/include -I/usr/local/opt/libzip/lib/libzip/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/jemalloc/include -I/usr/local/opt/tbb/include -I/usr/local/opt/openssl/include -I/usr/local/opt/oniguruma/include -I/usr/local/opt/libelf/include/libelf -I/usr/local/opt/gettext/include -I/usr/include/security -I/usr/local/Cellar/hhvm/3.9.1/src/hphp -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/double-conversion/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/fastlz -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/timelib -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/libafdt/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/libmbfl -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/libmbfl/mbfl -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/libmbfl/filters -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/proxygen/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/folly -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/folly/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/thrift/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle/src -I/usr/local/Cellar/hhvm/3.9.1/src/third-party -I/usr/local/Cellar/hhvm/3.9.1/src    -fpermissive -o CMakeFiles/wangle.dir/src/wangle/ssl/TLSTicketKeyManager.cpp.o -c /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle/src/wangle/ssl/TLSTicketKeyManager.cpp
> [ 28%] Linking CXX static library libwangle.a
> cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/wangle.dir/cmake_clean_target.cmake
> cd /usr/local/Cellar/hhvm/3.9.1/src/third-party/wangle && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/wangle.dir/link.txt --verbose=1
> /usr/bin/ar cq libwangle.a  CMakeFiles/wangle.dir/src/wangle/acceptor/Acceptor.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/ConnectionManager.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/LoadShedConfiguration.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/ManagedConnection.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/SocketOptions.cpp.o CMakeFiles/wangle.dir/src/wangle/acceptor/TransportInfo.cpp.o CMakeFiles/wangle.dir/src/wangle/channel/Pipeline.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/ByteToMessageCodec.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldBasedFrameDecoder.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LengthFieldPrepender.cpp.o CMakeFiles/wangle.dir/src/wangle/codec/LineBasedFrameDecoder.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/Codel.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/CPUThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/GlobalExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/IOThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/concurrent/ThreadPoolExecutor.cpp.o CMakeFiles/wangle.dir/src/wangle/deprecated/rx/Dummy.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/PasswordInFile.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLContextManager.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLSessionCacheManager.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/SSLUtil.cpp.o CMakeFiles/wangle.dir/src/wangle/ssl/TLSTicketKeyManager.cpp.o
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libwangle.a(Dummy.cpp.o) has no symbols
> /usr/bin/ranlib libwangle.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libwangle.a(Dummy.cpp.o) has no symbols
> [ 28%] Built target wangle
> make: **\* [all] Error 2

**Comment by denji** [comment]
This tap has been **deprecated** in favor of the [official tap](https://github.com/hhvm/homebrew-hhvm). After almost  two years of work the [official support](http://hhvm.com/blog/10043/experimental-mac-os-x-support) for OSX has been released.

**Comment by akaias** [comment]
ah okay, thanks ... didn't know that, gonna switch over to the mentioned one
